name: CI - Pytest

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html

      # 確認檔案與可匯入性（若失敗，log 會很清楚）
      - name: Sanity checks
        run: |
          ls -R
          python - << 'PY'
          import os, sys
          assert os.path.exists('tests/test_app.py'), "tests/test_app.py 不存在"
          sys.path.append(os.getcwd())
          __import__('app')
          print("✅ found tests/test_app.py 且可匯入 app.py")
          PY

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q --maxfail=1 --disable-warnings --html=report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
